# Generated by Django 4.0.3 on 2022-05-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name of the venue')),
                ('address', models.CharField(max_length=120, verbose_name='street address')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('state', models.CharField(max_length=2, verbose_name='state')),
                ('website', models.URLField(verbose_name='external venue website')),
                ('image', models.URLField(verbose_name='link to an image of venue')),
            ],
        ),
    ]
