# Generated by Django 4.0.3 on 2022-05-16 06:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenueapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Name must be greater than 1 character')], verbose_name='name of the venue'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seating_rating', models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=1, verbose_name='seating')),
                ('sound_rating', models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=1, verbose_name='sound')),
                ('scene_rating', models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=1, verbose_name='scene')),
                ('bathrooms_rating', models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=1, verbose_name='bathrooms')),
                ('overall_rating', models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=1, verbose_name='overall')),
                ('comments', models.TextField(max_length=500, verbose_name='comments')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenueapp.venue')),
            ],
        ),
    ]
