# Generated by Django 4.0.3 on 2022-05-16 03:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenueapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Name must be greater than 1 character')], verbose_name='name of the venue'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(default=1, verbose_name='rate your overall experience')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenueapp.venue')),
            ],
        ),
    ]
