# Generated by Django 4.0.3 on 2022-05-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenueapp', '0003_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='genres',
            field=models.ManyToManyField(to='revenueapp.genre'),
        ),
    ]
