# Generated by Django 4.0.3 on 2022-05-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenueapp', '0004_venue_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
