# Generated by Django 4.0.3 on 2022-05-17 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenueapp', '0005_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Name must be greater than 1 character')], verbose_name='name of the venue'),
        ),
    ]
