# Generated by Django 4.0.3 on 2022-05-17 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenueapp', '0006_alter_venue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenueapp.venue', unique=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='genres',
            field=models.ManyToManyField(help_text='Select multiple genres with ctrl/cmd', to='revenueapp.genre'),
        ),
    ]
