# Generated by Django 4.0.3 on 2022-05-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenueapp', '0007_alter_review_venue_alter_venue_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='genres',
            field=models.ManyToManyField(help_text='HINT: Select multiple genres with ctrl/cmd.', to='revenueapp.genre'),
        ),
    ]
