# Generated by Django 4.0.3 on 2022-06-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenueapp', '0008_alter_venue_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='zipcode',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
